server:
  port=8080

spring:
  application:
    name=Movie
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/movie
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

    properties:
      hibernate:
        format-sql: true
